version: '3'

services:
    php:
        image: php:8.2-fpm
        volumes:
            - '.:/var/www/html'
        ports:
            - '9000:9000'
        user: "1002:1002"
        networks:
            - FastReading
    nginx:
        image: nginxinc/nginx-unprivileged:latest
        restart: always
        volumes:
            - '.:/var/www/html'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './nginx/.htpasswd:/etc/nginx/.htpasswd'
        ports:
            - '80:80'
        user: "1002:1002"
        depends_on:
            - php
            - node
        links:
            - php
        networks:
            - FastReading
    node:
        image: node:latest
        restart: always
        volumes:
            - '.:/var/www'
        working_dir: '/var/www'
        ports:
            - '3000:3000'
        user: "1002:1002"
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: /bin/sh -c "npm install --cache /var/www/.npm && npm run build"
        networks:
            - FastReading
networks:
    FastReading:
        driver: bridge
