version: '3'

services:
    php:
        image: php:8.2-fpm
        volumes:
            - '.:/var/www/html'
        ports:
            - '9000:9000'
        networks:
            - FastReading
    nginx:
        image: nginx:latest
        restart: always
        volumes:
            - '.:/var/www/html'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - '80:80'
        depends_on:
            - php
            - node
        links:
            - php
        networks:
            - FastReading
    node:
        image: node:latest
        restart: always
        volumes:
            - '.:/var/www'
        working_dir: '/var/www'
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: /bin/sh -c "npm install && npm run dev"
        networks:
            - FastReading
networks:
    FastReading:
        driver: bridge
